# Generated by Django 5.2.17 on 2026-09-15 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_optiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_values', to='products.optiontype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('option_type', 'value'), name='unique_option_value_per_type')],
            },
        ),
    ]
