# Generated by Django 5.2.17 on 2026-09-16 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_optionvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_options', to='products.optionvalue')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_options', to='products.productvariant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product_variant', 'option_value'), name='unique_product_variant_option_value')],
            },
        ),
    ]
