# Generated by Django 5.2.17 on 2026-09-10 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='product_collections.collection')),
            ],
            options={
                'db_table': 'collection_highlights',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
